### ISSUE TITLE
make weight consistent

### ISSUE THREAD

**Issue by anvinh** [FourZeroOne/python_dhl_germany#1]
Hi Johannes,

erstmal danke für deine Repo. Es hat mir sehr viel geholfen. Ich würde gerne etwas dazu beitragen und würde dir meine Vorschläge erstmal vorstellen. Wenn es passt, implementiere ich und schicke dir einen Pull Request:
- "netWeightInKG": position["weight_unit"] / 1000.0: -> Ich vermutte mal für deinen Use Case ist es einfacher in Gram einzugeben als in kg, deswegen der Code? Und an weight_unit denke ich "kg" oder "g" und nicht eine Zahl. Ich würde hier auf position["weight_in_kg_net"] ändern
https://github.com/FourZeroOne/python_dhl_germany/blob/3353e0b96789a415199df3be63247b142e15b95f/dhl/__init__.py#L254
- Die obere Änderung macht dann die Angabe für weight_total konsistent in kg. Ich würde die Variable weight_total in weight_in_kg_total umbenennen
https://github.com/FourZeroOne/python_dhl_germany/blob/3353e0b96789a415199df3be63247b142e15b95f/dhl/__init__.py#L209
- Passend zu dieser Änderung dann die Anpassung der Zahlen in den Testen, von g zu kg.

Sonst habe ich eine Frage bezüglich is_premium. Ist diese Feature von dem Shipment schon durch das DHL Produkt, zB V53WPAK für DHL Paket International, definiert? Wenn ich das Produkt benutze, wird die Sendung trotzdem Premium wenn ich aus versehen is_premium=False setze?
https://github.com/FourZeroOne/python_dhl_germany/blob/3353e0b96789a415199df3be63247b142e15b95f/dhl/__init__.py#L198

Viele Grüße
Vinh

**Comment by joeimer** [comment]
Danke für den Input @anvinh

"weight_unit" war gedacht als "Gewicht pro Unit". Aber der Name ist irreführend. Da geb ich dir Recht. Ich würde das entsprechend anpassen. 
**weight + weight_unit + weight_total**

Ich würde dann die weight_unit für init hinzufügen.

weight_unit versteht dann g und kg. Standard: kg.


zu deiner zweiten Frage:
Der Service Premium ist ein Zusatzprodukt von DHL.  Wenn das Produkt Premium standardmäßig beinhaltet, musst du Premium nicht nochmals auswählen und kannst es auch als False übergeben (was aber eh standard ist). Mir ist bisher nur der Fall bei Warenpost Int. bekannt, dass dort Premium aktiviert werden muss, um eine TrackingNummer zu erhalten.
Die pylib übergibt Premium nicht aktiv. Wenn du also is_premium auf False setzt, wäre es das gleiche, als wenn dieses Feature gar nicht hinzugefügt worden wäre.
Soll heißen: du kannst is_premium auf False stehen lassen, aber für DHL Paket International dennoch ein Trackingnummer bekommen.

**Comment by anvinh** [comment]
Sehr cool. Danke für deine Erklärung @joeimer. Soll ich die Anpassung vornehmen und dir ein pull request schicken oder machst du es? Es war mir nicht ganz klar. Du kannst es gerne machen, ich werde es zu meinem Fork pullen dann. VG, Vinh

**Comment by joeimer** [comment]
@anvinh bin schon dran. Ist gleich fertig.

**Comment by joeimer** [comment]
@anvinh habs angepasst. Schau mal, ob das so für dich ok ist

**Comment by joeimer** [comment]
@anvinh schaus dir nochmals an. Ich hab noch None als Value dazu gepackt. Dann wird default mäßig auch kg genommen.
