### ISSUE TITLE
create classes for shipper, receiver, order, and position

### ISSUE THREAD

**Issue by anvinh** [FourZeroOne/python_dhl_germany#2]
Wie wäre es wenn shipper, receiver und order seine eigene Klassen haben. 2 Vorteile sehe ich:
- Bei der Erstellung ihre Instances kann man in einer IDE wie PyCharm die Attributes sehen. Als ich deine Repo über DHL Forum gefunden habe, wusste ich nicht wie die shipper, receiver und order aussehen sollen, bis ich Beispiele in den Testen gefunden habe und irgendwann danach hast du ein Beispiel in README reingepackt.
- Indirekte Dokumentation, welche Felder + wie die Struktur zu erwarten sind.

ok wenn man dieses Design macht, dann braucht man auch die Klasse Position als input für Order

Was hälst du davon?
VG
Vinh

https://github.com/FourZeroOne/python_dhl_germany/blob/master/README.md#usage

**Comment by joeimer** [comment]
ich hab schon schemas für die Dicts jetzt angelegt. Kommt dann mit der neuen Version. Damit sollte das ganze etwas übersichtlicher werden.

Klassen an sich finde ich sehr gut. Allerdings: die Idee für diese Lib war eher als Layer für andere Systeme gedacht. Und da wollte ich so flexibel bleiben, wie ich nur kann. So kann man seine eigene Klasse implementieren und ein einfaches Mapping zu Dict erstellen. Weiß nicht, ob ein Class -> Class Mapping einfacher/schneller ist. Dazu hab ich noch zu wenig Input.
In welcher Form liegen denn deine Rohdaten vor?

Da ich mit Microservices und MongoDB arbeite, muss ich mit sehr viel dicts arbeiten. Und das jedes mal in eine Klasse zu konvertieren, nur dass der Code dann schöner ist, finde ich etwas Ressourcen fressend. Ich hab zB meinen ganzen Code von MongoEngine auf pymongo umgstellt, da die Konvertierung zur Klasse und dann wieder zu dict einfach zu lange gedauert hat. Für eine API zahlt da leider jede MS. Ich weiß nicht, ob es hier mittlerweile einen einfachen, schöneren und schnelleren Weg gibt. In JS ist es zB viel angenehmen mit dicts zu arbeiten. Wenn du dazu mehr Infos hast, wäre ich froh über deinen Input!

OrderShipmentResponse (DHL) ist auch ein dict. Bin mir noch nicht sicher, ob man hier dann eine Klasse zurückgeben sollte. Das könnte man dann aber auch via variable steuern

**Comment by anvinh** [comment]
Ja das macht Sinn wie du beschreibst. Je mehr und detaliert man macht, desto weniger flexibel ist das ganze. Ich hatte auch den Gedanke, die Klassen auf meiner Seite zu implementieren. Nach deiner Antwort muss ich nachdenken, ob es vllt auch over engineered wäre, Klassen zu erstellen.

Meine Rohdaten sind in einem Pandas Dataframe. Ich bereite Labels in Batch vor. Früher war es noch half-manuell, dass ich CSV mit ganz viele Daten von Labels erstellt, im Geschäftskundenportal in Batch hochgeladen und drucken lassen habe.
